import {
  SiClevercloud,
  SiExpress,
  SiFoodpanda,
  SiFramer,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiJavascript,
  SiJsonwebtokens,
  SiMongodb,
  SiMongoose,
  SiMysql,
  SiNetlify,
  SiNextdotjs,
  SiNodedotjs,
  SiPostman,
  SiPrisma,
  SiRadixui,
  SiReact,
  SiReactquery,
  SiRedis,
  SiRedux,
  SiRender,
  SiShadcnui,
  SiSocketdotio,
  SiTailwindcss,
  SiTypescript,
  SiVercel,
  SiZod,
} from "react-icons/si";

export const TECH_STACK = [
  { name: "TypeScript", icon: SiTypescript, iconColor: "#3178C6" },
  { name: "JavaScript", icon: SiJavascript, iconColor: "#F7DF1E" },
  { name: "React", icon: SiReact, iconColor: "#61DAFB" },
  { name: "Next.js", icon: SiNextdotjs, iconColor: "#000000" },

  { name: "Node.js", icon: SiNodedotjs, iconColor: "#5FA04E" },
  { name: "Express.js", icon: SiExpress, iconColor: "#000000" },
  { name: "Socket.IO", icon: SiSocketdotio, iconColor: "#010101" },

  { name: "Redis", icon: SiRedis, iconColor: "#FF4438" },
  { name: "MySQL", icon: SiMysql, iconColor: "#4479A1" },
  { name: "MongoDB", icon: SiMongodb, iconColor: "#47A248" },
  { name: "Prisma", icon: SiPrisma, iconColor: "#2D3748" },
  { name: "Mongoose", icon: SiMongoose, iconColor: "#880000" },

  { name: "TanStack Query", icon: SiReactquery, iconColor: "#000000" },
  { name: "Zustand", icon: SiFoodpanda, iconColor: "#000000" },
  { name: "Redux", icon: SiRedux, iconColor: "#764ABC" },

  { name: "ShadcnUI", icon: SiShadcnui, iconColor: "#000000" },
  { name: "Radix UI", icon: SiRadixui, iconColor: "#000000" },
  { name: "Tailwind CSS", icon: SiTailwindcss, iconColor: "#06B6D4" },
  { name: "Framer Motion", icon: SiFramer, iconColor: "#0055FF" },
  { name: "Zod", icon: SiZod, iconColor: "#408AFF" },
  {
    name: "JWT",
    icon: SiJsonwebtokens,
    iconColor: "#000000",
  },

  { name: "Git", icon: SiGit, iconColor: "#F03C2E" },
  { name: "GitHub", icon: SiGithub, iconColor: "#181717" },
  {
    name: "GitHub Actions",
    icon: SiGithubactions,
    iconColor: "#2088FF",
  },
  { name: "Postman", icon: SiPostman, iconColor: "#FF6C37" },

  { name: "Vercel", icon: SiVercel, iconColor: "#000000" },
  { name: "Netlify", icon: SiNetlify, iconColor: "#00C7B7" },
  { name: "Render", icon: SiRender, iconColor: "#000000" },
  { name: "Cleaver Cloud", icon: SiClevercloud, iconColor: "#171C36" },
];
